version: '3.8'

services:
  # Frontend (your existing Next.js app)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001/ws
    depends_on:
      - drone-db-service
      - realtime-service
    networks:
      - flyos-network
    restart: unless-stopped

  # TimescaleDB database
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: flyos_admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: flyos_db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./services/drone-db-service/migrations/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - flyos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flyos_admin -d flyos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for real-time data
  redis:
    image: redis:7
    command: redis-server --appendonly yes --requirepass secure_redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - flyos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Service
  drone-db-service:
    build:
      context: ./services/drone-db-service
      dockerfile: Dockerfile
    depends_on:
      - timescaledb
      - redis
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=postgresql://flyos_admin:secure_password@timescaledb:5432/flyos_db
      - REDIS_URL=redis://default:secure_redis_password@redis:6379
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "4001:4001"
    networks:
      - flyos-network
    restart: unless-stopped

  # Real-time Service
  realtime-service:
    build:
      context: ./services/realtime-service
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=4002
      - REDIS_URL=redis://default:secure_redis_password@redis:6379
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "4002:4002"
    networks:
      - flyos-network
    restart: unless-stopped

networks:
  flyos-network:
    driver: bridge

volumes:
  timescaledb_data:
  redis_data:
